CREATE TABLE [dbo].[Cars](
   ID          INT         IDENTITY(1, 1) NOT NULL PRIMARY KEY
  ,Name        VARCHAR(35) NOT NULL
  ,Owner       VARCHAR(16) NOT NULL
  ,AppearsIn   VARCHAR(38) NOT NULL
  ,Description VARCHAR(617) NOT NULL
);
INSERT INTO dbo.Cars(Name,Owner,AppearsIn,Description) VALUES ('1970 Dodge Charger','Vin Diesel','The Fast And The Furious','At the end of the first film, Dominic Toretto (Vin Diesel) races Brian O''Conner (Paul Walker) in his father''s 1970 Dodge Charger, which is said to have 900 hp. After just missing being hit by a freight train, the Charger hits a truck and flips through the air. Although it looks like the Dodge muscle car''s racing days are over, the car returns for films 4 and 5 to break Toretto out of a prison transport bus.');
INSERT INTO dbo.Cars(Name,Owner,AppearsIn,Description) VALUES ('Nissan Skyline GT-R R34','Paul Walker','The Fast and the Furious: Tokyo Drift.','At the beginning of 2003''s "2 Fast 2 Furious," Brian O''Conner drives an R34-generation Nissan Skyline GT-R. He enters the car in a four-way street race, where he jumps the twin-turbo, all-wheel-drive coupe off a bridge before getting car-tasered by the cops. The R34 returns in the fourth installment, though it''s unclear if O''Conner installed a "Gallo 12" or "Gallo 24" engine this time around.');
INSERT INTO dbo.Cars(Name,Owner,AppearsIn,Description) VALUES ('1994 Toyota Supra Mk IV','Paul Walker','The Fast And The Furious','The Supra was one of the star cars of the first film, rescued by O''Conner from a junkyard and brought back to life in Toretto''s garage. Despite not being a twin-turbo model (revealed when the hood is opened), the crew is impressed with O''Conner''s find. It''s at this point that one of the most quotable lines of the movie is uttered: "You know what? This will decimate all, after you put about 15 grand in it or more. If we have to, overnight parts from Japan." On the car''s maiden drive, O''Conner and Toretto race and beat a Ferrari F355 Spider that they''re told is "more than [they] can afford, pal."');
INSERT INTO dbo.Cars(Name,Owner,AppearsIn,Description) VALUES ('1967 Ford Mustang Fastback','Lucas Black','The Fast and the Furious: Tokyo Drift.','In the final scenes of "The Fast and the Furious: Tokyo Drift," Sean Boswell (Lucas Black) drives a 1967 Ford Mustang formerly owned by his father. The twist is that this pony needs a new engine, and being that the movie takes place in Japan, the natural choice is the twin-turbo, 2.6-liter RB26 inline-six out of the Nissan Skyline GT-R. Forget for a moment the amount of fabrication such a swap would require, and you can accept that the Nissan engine is the only choice for the Mustang''s new beating heart. Whether you call it blasphemy or car pornography, there''s no denying that this Mustang is one unique build.');
INSERT INTO dbo.Cars(Name,Owner,AppearsIn,Description) VALUES ('2001 Nissan Silvia S15 Spec-S','Lucas Black','The Fast and the Furious: Tokyo Drift.','The 2001 Nissan Silvia S15 Spec-S is first seen when Sean Boswell first comes to the parking garage where drift races are held. Takashi, confronted Sean for talking to Neela, his girlfriend. Before its untimely death, this car had Earl''s Performance steel braided lines with anodized fittings, a C-West body kit, a GT rear wing, Ganador side mirrors, and Volk Racing grey GT-7 No.0355 19" rims.');
INSERT INTO dbo.Cars(Name,Owner,AppearsIn,Description) VALUES ('2006 Mitsubishi Lancer Evolution IX','Lucas Black','The Fast and the Furious: Tokyo Drift.','After Sean kills Han''s Silvia, Han lets him use this Evo IX instead. It has an Evo VIII end, which can lead to confusion -- but it''s an Evo IX. Engine is a 2-liter turboed DOHC 4G63 with an RMR air intake system and downpipe. Front driveshafts were disconnected to make drifting an AWD car possible. Appearance mods include an APR body kit and rear wing, APR Racing side mirrors, and Ray''s Wheels G-Games 99B 19" rims.');
INSERT INTO dbo.Cars(Name,Owner,AppearsIn,Description) VALUES ('2003 Honda (Acura) NSX','Jordana Brewster','Fast And Furious (4)','The NSX driven by Mia Toretto features red leather seats, rear-wheel drive, and a 6-speed manual transmission.This model in stock configuration is powered by a C32B V6 producing 290 bhp. The car used for the films is heavily modified including NSX-R suspension, brakes, wheels, exterior parts, and other upgrades and produces 295 whp and 213 lbs. ft torque.');
INSERT INTO dbo.Cars(Name,Owner,AppearsIn,Description) VALUES ('2012 Lexus LF-A','Sung Kang','Fast Five','At the end of Fast Five, the major characters are shown living their new lives with the money from the vault. Han and Gisele speed along a highway towards Berlin in the Lexus LFA. Gisele sits in Han''s lap as he drives. After a couple of kisses, Gisele asks Han where they are headed. When Han suggests Madrid, Gisele remembers that Han wanted to go to Tokyo. Han says they will make it there eventually, and they speed off towards Berlin. The LFA never makes another appearance in the movies.');
INSERT INTO dbo.Cars(Name,Owner,AppearsIn,Description) VALUES ('1993 Mazda RX-7 (Veilside)','Sung Kang','The Fast and the Furious: Tokyo Drift.','The 1997 Mazda RX-7 is one of Han Seoul-Oh''s primary cars when traveling through the city of Tokyo. Following Sean Boswell first failed drift race against the Drift King, Takashi, Han uses the RX-7 to recruit Sean into his business with Takashi, who was indebted to him after destroying his 2001 Nissan Silvia S-15 Spec-S.');
INSERT INTO dbo.Cars(Name,Owner,AppearsIn,Description) VALUES ('Plymouth Road Runner','Vin Diesel','Fast 6','The Plymouth Road Runner first appears in The Fast and the Furious: Tokyo Drift, driven by Dominic Toretto, who says "I won it from my friend Han a few years ago" when talking to Sean Boswell. This car featured a grey paint job and had black wheels.');
